language: node_js
node_js:
  - lts/*
install:
  - npm install
  - npm i lerna -g
  - lerna bootstrap
script:
  - npm run cover
  - npm run docs:build
deploy:
  provider: pages
  skip_cleanup: true
  local_dir: packages/docs/docs/.vuepress/dist
  github_token: $GITHUB_TOKEN
  keep_history: true
  on:
    branch: master
